version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # Native
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  hft_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hft_app
    volumes:
      - .:/app
    depends_on:
      - kafka
      - clickhouse
    command: ["bash", "entrypoint.sh"]
    environment:
      - PYTHONUNBUFFERED=1

  streamlit_ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["streamlit", "run", "hft_trading_system.py"]
    depends_on:
      - clickhouse

volumes:
  clickhouse_data: