# -----------------------------------------------------------------------------
#  docker-compose-hft.yml   - High-Frequency Trading System
# -----------------------------------------------------------------------------

services:
  # ------------------------------------------------------------ CLICKHOUSE
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_hft
    ports:
      - "8123:8123"     # HTTP
      - "9000:9000"     # Native TCP
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER:      default
      CLICKHOUSE_PASSWORD:  secret
      CLICKHOUSE_DB:        default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # --------------------------------------------------------------- HFT APP
  hft_app:
    build: .
    container_name: hft_app
    env_file: [.env]                 # BINANCE_* and CLICKHOUSE_PASSWORD
    environment:
      PYTHONUNBUFFERED: "1"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASS: secret
      DRY_RUN: 0                      # Live trading mode
      KAFKA_ENABLED: 0
      LIQUIDATION_ENABLED: 0
      BINANCE_API_KEY: ${BINANCE_API_KEY:-YOUR_BINANCE_API_KEY}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET:-YOUR_BINANCE_SECRET_KEY}
    volumes:
      - .:/app:ro                    # read-only live code
    depends_on: [clickhouse]
    entrypoint: []
    command: ["/bin/bash", "hft_entrypoint.sh"]

  # ----------------------------------------------------------- STREAMLIT UI
  streamlit_ui:
    build: .
    container_name: streamlit_ui_hft
    ports: ["8502:8501"]               # Changed to avoid port conflict
    env_file: [.env]                    # only ClickHouse creds needed
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASS: secret
      DRY_RUN: 0
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME:-admin}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:-trading123}
    depends_on: [clickhouse]

    # run Streamlit directly, bypassing /app/entrypoint.sh
    entrypoint: []
    command: ["streamlit", "run", "ui_dashboard_fixed.py", "--server.port=8501", "--server.address=0.0.0.0"]

# ---------------------------------------------------------------- VOLUMES
volumes:
  clickhouse_data:
