services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on: [zookeeper]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  hft_app:
    build: .
    container_name: hft_app
    env_file:                # ← inject API keys from .env
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:                 # optional; keep read-only if you only need logs
      - .:/app:ro
    depends_on:
      - kafka
      - clickhouse
    # uses ENTRYPOINT from Dockerfile

  streamlit_ui:
    build: .
    container_name: streamlit_ui
    ports: ["8501:8501"]
    depends_on: [clickhouse]
    command:
      - streamlit
      - run
      - ui_dashboard.py
      - "--server.port=8501"
      - "--server.address=0.0.0.0"

volumes:
  clickhouse_data: